import NavigationMenu from '../../components/admin/cms/NavigationMenu';

export const metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavigationMenu>{children}</NavigationMenu>
      </body>
    </html>
  );
}
